#!/usr/bin/env zsh
set -e

function main() {
    if [ "$#" -eq 0 ]; then
        echo "Must provide script arg with name of function to be called"
        exit 1
    else
        # If this script was called with arguments, then we build for docker
        #   The following expects the first argument to be the function name
        $@
    fi
}

function bootstrap_vim() {
    _message
    if [[ ! -d ~/.config/vim/autoload/plug.vim ]]; then
        curl --create-dirs -fsSLo ~/.config/vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
    fi
    zsh -c "yes '\n' | vim +PlugUpdate +PlugClean! +PlugUpdate +qall"
}

function bootstrap_antibody() {
    _message
    if [[ ! -x "$(command -v antibody)" ]]; then
        curl -sfL git.io/antibody | sh -s - -b ~/.local/bin
    else
        echo "  > Antibody already installed..."
    fi
}

function bootstrap_zprezto() {
    _message

    if [[ ! -d "${ZDOTDIR:-$HOME}/zprezto" ]]; then
        git clone --quiet --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/zprezto" >/dev/null 2>&1
    else
        echo "  > zprezto already installed..."
    fi
}
function bootstrap_tmux() {
    _message

    if [[ ! -d "${XDG_CONFIG_HOME}/tmux/plugins/tpm" ]]; then
        git clone --quiet https://github.com/tmux-plugins/tpm "${XDG_CONFIG_HOME}/tmux/plugins/tpm"
    else
        echo "  > tmux already bootstrapped..."
    fi
}
function update_yadm_remote() {
    echo 'hello'
    _message

    cd ~/.config/yadm/repo.git
    if [[ ! "$(git remote -v)" == *"$http"* ]]; then
        echo "No http in git remote"
        cd -
        exit 0
    fi
    GIT_REMOTE=$(git remote -v | head -1 | sed 's| (fetch)||g' | sed 's|^origin\t||g' | awk -F '/' '{print "git@"$(NF-2)":"$(NF-1)"/"$NF}')
    git remote set-url origin ${GIT_REMOTE}
    cd -
}

function _message() {
    caller=$(echo $funcstack[2])
    base_message=$(echo $caller | sed -r 's/(\<|_)([[:alnum:]])/\U \2/g')
    printf "⮀%s...\n" $base_message
}

#####################################################################
# Run the main program
main "$@"
