#!/usr/bin/env bash

echo "Bootstraping Vim"
if [[ ! -d $XDG_CONFIG_HOME/vim/autoload/plug.vim ]]; then
  curl --create-dirs -fsSLo $XDG_CONFIG_HOME/vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
fi
bash -c "yes '\n' | vim --not-a-term +PlugUpdate +PlugClean! +PlugUpdate +qall"