#!/usr/bin/env zsh

source ~/.zshenv

echo "Bootstraping Vim"
if [[ ! -d ~/.config/vim/autoload/plug.vim ]]; then
  curl --create-dirs -fsSLo ~/.config/vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
fi
zsh -c "yes '\n' | vim +PlugUpdate +PlugClean! +PlugUpdate +qall"

if [[ ! -x "$(command -v antibody)" ]]; then
    curl -sfL git.io/antibody | sh -s - -b ~/.local/bin
fi