#!/usr/bin/env zsh
source ~/.zshenv

HERE=$(cd `dirname "${0:A}"` && pwd)

$HERE/hack/bootstrapper bootstrap_vim
$HERE/hack/bootstrapper bootstrap_antibody
$HERE/hack/bootstrapper bootstrap_zprezto
$HERE/hack/bootstrapper bootstrap_tmux