
" Environment
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
" set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" let configs = ['10-general', '20-ui', '30-commands', '40-plugins', '50-plugin-settings']
" for config in configs
"   let config_path=expand("$XDG_CONFIG_HOME/vim/config/".config.".vim")
"   if filereadable(config_path)
"     execute 'source' config_path
" endfor

for config in split(glob('$XDG_CONFIG_HOME/vim/config/*.vim'), '\n')
  if filereadable(config)
    exe 'source' config
  endif
endfor