#!/usr/bin/env zsh
set -euo pipefail

HERE=$(cd `dirname "${0:A}"` && pwd)

$HERE/../hack/bootstrapper bootstrap_vim
$HERE/../hack/bootstrapper bootstrap_antibody
$HERE/../hack/bootstrapper bootstrap_zprezto